language: generic

dist: trusty

git:
  depth: 3

script:
  - python3 --version
  - ./generate-db
  - ./run-tests

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
