language: python

dist: trusty

python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly

git:
  depth: 3

script:
  - ./generate-db
  - ./run-tests

notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
    on_failure: always
